"""add paragraphs column to conversion_tasks

Revision ID: 20260517_1330
Revises: 20260530_120000
Create Date: 2026-05-17 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260517_1330'
down_revision = '20260530_120000'  # 依赖于 add_conversion_history_to_users
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversion_tasks', sa.Column('paragraphs', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversion_tasks', 'paragraphs')
    # ### end Alembic commands ###
